name: unicaf

services:
  frontend:
    image: unicaf-frontend # the image name
    build: ./frontend/
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

  backend:
    image: unicaf-backend
    build: ./backend/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./backend/src:/backend/src # map the host src dir to the container's src for hot reloads

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: unicaf-db
    ports:
      - "5432:5432"
    volumes: # maps the unicaf-data volume to the internal postres anon volume
      - unicaf-data:/var/lib/postgresql/data
      

volumes:
  unicaf-data:
