-- THIS FILE WILL BE RAN AUTOMATICALLY BY THE POSTGRES IMAGE, CHECK OUT THE COMPOSE FILE
CREATE TABLE IF NOT EXISTS "Person" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    credit DOUBLE PRECISION DEFAULT 0.0,
    bonus_points INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "Table" (
    id SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "Seat" (
    id SERIAL PRIMARY KEY,
    table_id INTEGER NOT NULL REFERENCES "Table"(id),
    status VARCHAR(20) NOT NULL DEFAULT 'free'
        CHECK (status IN ('free', 'occupied')),
    person_id INTEGER REFERENCES "Person"(id),
    expires_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "QueueEntry" (
    id SERIAL PRIMARY KEY,
    person_id INTEGER NOT NULL UNIQUE REFERENCES "Person"(id),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Reservation" (
    id SERIAL PRIMARY KEY,
    seat_id INTEGER NOT NULL UNIQUE REFERENCES "Seat"(id),
    person_id INTEGER NOT NULL REFERENCES "Person"(id)
);
