name: CI

# triggers whenever code is pushed on the main branch / a pull request to the main branch is created
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # an anction that copies the repo to github virtual machine
      - name: Checkout
        uses: actions/checkout@v4

      # try to build the project
      - name: Build
        run: docker compose build
